language: ruby
cache: bundler
rvm:
- 2.1.0
- 2.0.0
before_install:
- gem update --system
- gem update bundler
before_script:
- bundle exec rake db:create db:migrate --trace
install:
- bundle install --jobs=1 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}