language: ruby
cache: bundler
rvm:
- 2.2.0
- 2.1.0
- 2.0.0
before_install:
- gem update --system
- gem update bundler
before_script:
- rake db:create db:migrate --trace
matrix:
  allow_failures:
    - rvm: jruby-head